<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResidentRepository extends EntityRepository
{
    public function queryLatest()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT p
                FROM AppBundle:Resident p                
                ORDER BY p.id DESC
            ')            
        ;
    }
    public function getByEventId($eventId)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT p
                FROM AppBundle:Resident p                
                ORDER BY p.id DESC
            ')            
        ;
    }

    public function findLatest()
    {
        $this->queryLatest()->getResult();
    }
    public function getOneResidentBySearch($firstName, $lastName, $email){
        $query = $this->getEntityManager()->createQuery(
            'SELECT p from AppBundle:Resident p
             WHERE p.firstName = :firstName AND
                   p.lastName  = :lastName  AND
                   p.email     = :email
            '            
        )->setParameter('firstName', $firstName)
         ->setParameter('lastName', $lastName)
         ->setParameter('email', $email);
        return $query->getOneOrNullResult();
    }
}
